### ISSUE TITLE
jupyterlab_h5web is installable through conda-forge

### ISSUE THREAD

**Issue by srmnitc** [silx-kit/jupyterlab-h5web#100]
I made a recipe for jupyterlab_h5web in conda-forge: https://github.com/conda-forge/jupyterlab-h5web-feedstock

Therefore, it is installable through `conda install -c conda-forge jupyterlab-h5web`. It might be good to mention this in the README and other documentation. I would also be happy to add any of the developers as maintainers of the package.

**Comment by t20100** [comment]
Great, thanks! 🎉 

I made a [PR](https://github.com/conda-forge/staged-recipes/pull/20358) for it that wasn't merged, you can add me as maintainer of the conda package.

**Comment by srmnitc** [comment]
Done, https://github.com/conda-forge/jupyterlab-h5web-feedstock/pull/3. Thanks!
