### ISSUE TITLE
Jupyter-lab is not giving the graphical display but just showing the object

### ISSUE THREAD

**Issue by alexreevesy** [silx-kit/jupyterlab-h5web#105]
When I run the example for your package the object: <jupyterlab_h5web.widget.H5Web object> is displayed instead of the graphical interface- what am I doing wrong:).

**Comment by loichuder** [comment]
This can happen when using the classical notebook interface instead of JupyterLab. 

Did you launch your Jupyter app via `jupyter lab` ?

If you did, could you tell me which version of JupyterLab you used ?

**Comment by alexreevesy** [comment]
Hi thanks a lot for getting back to me so quickly, I did launch a Jupyter lab - but I realized that in my environment it was not installed via pip yet! Now everything is working- many thanks:)

**Comment by loichuder** [comment]
Ha great to know :slightly_smiling_face:
