### ISSUE TITLE
Widen file extension association

### ISSUE THREAD

**Issue by jl-wynen** [silx-kit/jupyterlab-h5web#11]
We are typically working with files that have a different extension than `.h5` or `.hdf5`. Those can only be opened after renaming them as far as I can tell. Even the 'Open with' menu lists only the editor, not h5web.
It is probably not useful to list all custom extensions that people use. But it would be great if the viewer would not be tied to the file name.

**Comment by loichuder** [comment]
Hello @jl-wynen,

Thanks for trying the extension and for the feedback !

Unfortunately, the extension adds the h5web capabilities is by adding a new file type to JupyterLab. And the way to do this is by matching file extensions... 

I agree with you that as there is a lot of HDF5 custom extensions, it would be preferable to work around this so I will investigate. 

In the mean time, know that I will add NeXus extensions (`.nx`, '.nexus`) in the next release and you are welcome to suggest any HDF5 extension that might be useful to your work.

**Comment by jl-wynen** [comment]
I was trying NeXus files, so the addition you mentioned will do it for me :-) Thanks!

Unfortunately, I don't know a way this could be done in a general way.
