### ISSUE TITLE
Opening Virtual Datasets raises error: "Request failed with status code 500"

### ISSUE THREAD

**Issue by gudlot** [silx-kit/jupyterlab-h5web#112]
Dear h5web-Team,
I created a h5 file with a  virtual dataset. I am following, in general, this example: [https://github.com/h5py/h5py/blob/master/examples/eiger_use_case.py](url)
As a result, I get a h5 file, where data contains my 3D stack in '/data/'. 
I thought I check the content out in h5web because I work on a jupyterhub. I get "Request failed with status code 500"
What is the minimum requirement to visualize your own created h5 files with h5web, please? 
In silx, I am able to see my data. 
Thank you.

**Comment by loichuder** [comment]
I generated the file with the snippet you linked (https://github.com/h5py/h5py/blob/master/examples/eiger_use_case.py) and I could open the VDS with jupyterlab-h5web.

Perhaps it is an issue of jupyterlab-h5web version ? Which version do you use ?

**Comment by gudlot** [comment]
Cool that it works for you. How do you determine the version of jupyterlab-h5web, please?

**Comment by loichuder** [comment]
You can do one of the following:
- Open a "Terminal" in JupyterLab and type `pip list | grep jupyterlab-h5web`
- Open a notebook, type `!pip list | grep jupyterlab-h5web` in a cell and execute it
- Open a notebook and type
```python
from jupyterlab_h5web import __version__

print(__version__)
```
in a cell and execute it

**Comment by gudlot** [comment]
Thank you. It only worked in the terminal. Output: jupyterlab-h5web 1.3.0
I executed above example in a new notebook in my conda env. The files were created, I could not visualise them, my conda env does not in it jupyterlab-h5web. Nevertheless, when I load ESRF h5 files, I see them in jupyterlab-h5web.
That is what surprises me.

**Comment by loichuder** [comment]
> Output: jupyterlab-h5web 1.3.0 

I figured such: I tried with latest version (`7.1.1`) to make it work. `1.3.0` is quite old: you should ask the maintainer of the JupyterHub instance to update it.

> Nevertheless, when I load ESRF h5 files, I see them in jupyterlab-h5web.

Perhaps these do not have external VDS ? :shrug:

**Comment by gudlot** [comment]
I ask them for an update and see if this will resolve this issue! 
ESRF files seem to have links down to the single h5 files.  
Nevertheless, it should still work the visualisation with the h5web. I update you with new information.

**Comment by gudlot** [comment]
The version was updated and it works now! Thank you for your help. Much appreciated.
> Perhaps these do not have external VDS ?
Or proper linking. I continue to explore this feature.

**Comment by axelboc** [comment]
Great to hear!
