### ISSUE TITLE
Make the extension compatible for JupyterLab 4

### ISSUE THREAD

**Issue by loichuder** [silx-kit/jupyterlab-h5web#116]
JupyterLab v4 was released on May 15th: https://github.com/jupyterlab/jupyterlab/releases/tag/v4.0.0

I tested with release candidates before and it seems that there are issues arising in the back-end (front-end looks fine). This is perhaps due to updates in `jupyter-server`.

**Comment by axelboc** [comment]
You've probably [read the changelog](https://jupyterlab.readthedocs.io/en/latest/getting_started/changelog.html#v4-0) already but for the record, here are a couple of changes that may affect us:

> In JupyterLab 4, building on this feature, the Extension Manager now includes extensions from [pypi.org](https://pypi.org/search/?c=Framework+%3A%3A+Jupyter+%3A%3A+JupyterLab). This removes the build step from installation of extension when using Extension Manager.

> Notebook windowing: By rendering only the parts of a notebook that fit in the web browser viewport, JupyterLab is much more efficient. See an important note below.
> Notebook windowing might add side effects for example if some cell outputs are displaying [iframes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe). Therefore it is not yet the default value.

**Comment by Podolyakofs** [comment]
Good day,  

in JupyterLab v4 (RTC collab mode)  h5/nexus file can not be opened with mouse click or with "View HDF5 file content" button

from browser console I got:
```
317.4b15296eee150f75fe74.js?v=4b15296eee150f75fe74:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'selectedItems')
    at execute (317.4b15296eee150f75fe74.js?v=4b15296eee150f75fe74:1:7862)
    at g.execute (jlab_core.f68a597bc4700114bad4.js?v=f68a597bc4700114bad4:1:1606567)
    at t.open (317.4b15296eee150f75fe74.js?v=4b15296eee150f75fe74:1:8130)
    at j.openOrReveal (jlab_core.f68a597bc4700114bad4.js?v=f68a597bc4700114bad4:1:571854)
    at re.handleOpen (jlab_core.f68a597bc4700114bad4.js?v=f68a597bc4700114bad4:1:699863)
    at re.evtDblClick (jlab_core.f68a597bc4700114bad4.js?v=f68a597bc4700114bad4:1:701950)
    at re.handleEvent (jlab_core.f68a597bc4700114bad4.js?v=f68a597bc4700114bad4:1:693496)
```

<details><summary>Extension lists</summary>
<pre>
jupyter_lsp  enabled 
    - Validating...
      jupyter_lsp 2.2.0 OK
    jupyter_server_ydoc  enabled 
    - Validating...
      X is jupyter_server_ydoc importable?
    jupyterlab  enabled 
    - Validating...
      jupyterlab 4.0.2 OK
    jupyterlab_h5web  enabled 
    - Validating...
      jupyterlab_h5web 8.0.0 OK
</pre>
</details>
