### ISSUE TITLE
Dark theme incorrect NXline color

### ISSUE THREAD

**Issue by Podolyakofs** [silx-kit/jupyterlab-h5web#118]
Good day
Looks like that legend color changes with theme switch, but not the lines color. (Incorrect view in dark mode)

### Screenshots
![image](https://github.com/silx-kit/jupyterlab-h5web/assets/3431942/b63a56be-571e-4ea3-953b-ffffd3d478c8)
![image](https://github.com/silx-kit/jupyterlab-h5web/assets/3431942/c1b5330c-baaf-4759-b783-283506fb7bb2)

### Context

- OS: Ubuntu 22.04.2 LTS
- Browser: Chrome
- Version: 7.1.2
- JupyterLab version: 2.5.0

<details><summary>Extension lists</summary>
<pre>
 jupyterlab-h5web v7.1.2 enabled OK (python, jupyterlab_h5web)
jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)

jupyter_server_ydoc  enabled 
    - Validating...
      X is jupyter_server_ydoc importable?
    jupyterlab  enabled 
    - Validating...
      jupyterlab 3.6.3 OK
    jupyterlab_h5web  enabled 
    - Validating...
      jupyterlab_h5web 7.1.2 OK
</pre>
</details>

**Comment by loichuder** [comment]
Thanks for the report ! I will have a look.

**Comment by loichuder** [comment]
This should be fixed in latest version (8.0.0)
