### ISSUE TITLE
Support of loom files

### ISSUE THREAD

**Issue by Denebium** [silx-kit/jupyterlab-h5web#126]
Hi, I use the H5Web VScode extension, witch is very similar to this one. With the VScode extension, I am able to open loom files directly (a HDF5 file format for genetic data, see https://loompy.org/ ), would it be possible to add .loom to the supported file format ?

Thanks ! 

Link to the VScode extension : https://marketplace.visualstudio.com/items?itemName=h5web.vscode-h5web

**Comment by loichuder** [comment]
Sure ! Just out of curiosity, could you provide an example `.loom` file ?

Thanks

**Comment by Denebium** [comment]
Thanks a lot !

Here is the classical exemple of a loom test file, freely available on the 10x genomics website : https://support.10xgenomics.com/single-cell-gene-expression/datasets/3.0.0/pbmc_10k_v3

Along with specifications and specs for the format of loom files : 
https://linnarssonlab.org/loompy/format/index.html
