### ISSUE TITLE
Deprecated key words in the Trouble Shooting part of README

### ISSUE THREAD

**Issue by hz-xiaxz** [silx-kit/jupyterlab-h5web#131]
### Describe the bug

Good Day. I check on my jupyter lab version "4.1.4" where the `jupyter serverextension` key word returns `Jupyter command `jupyter-serverextension` not found.` This is same as the StackOverflow issue [https://stackoverflow.com/questions/77711472/jupyter-command-jupyter-serverextension-not-found](url) and can be solved accordingly by changing the command to `jupyter server extension list` .

### To Reproduce
go type `jupyter serverextension list` and you'll get the error message

### Expected behaviour

as above.
### Screenshots

![image](https://github.com/silx-kit/jupyterlab-h5web/assets/114814844/2e74e133-2589-4f4b-babf-053602ffdb8d)

### Context

- OS:   Linux version 3.10.0-1160.92.1.el7.x86_64
- Browser: No
- JupyterLab version: 4.1.4

<details><summary>Extension lists</summary>
<pre>
Paste the output from running `jupyter labextension list` and `jupyter serverextension list` from the command line here.
You may want to sanitize the paths in the output.--- also this template should be changed
`jupyter labextension list`
JupyterLab v4.1.4
/xxx/jupyter/labextensions
        ipyparallel-labextension v8.7.0 enabled OK
        jupyterlab-h5web v12.0.0 enabled OK (python, jupyterlab_h5web)
        @jupyter-notebook/lab-extension v7.1.1 enabled OK
        @jupyter-widgets/jupyterlab-manager v5.0.10 enabled OK (python, jupyterlab_widgets)
        @pyviz/jupyterlab_pyviz v3.0.1 enabled OK

`jupyter server extension list` 

Config dir: /xxx/.jupyter

Config dir: /xxx/etc/jupyter
    ipyparallel enabled
    - Validating ipyparallel...
Package ipyparallel took 0.2808s to import
A `_jupyter_server_extension_points` function was not found in ipyparallel. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
      ipyparallel 8.7.0 OK
    jupyter_lsp enabled
    - Validating jupyter_lsp...
Package jupyter_lsp took 0.0087s to import
A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
      jupyter_lsp 2.2.0 OK
    jupyter_server_terminals enabled
    - Validating jupyter_server_terminals...
Package jupyter_server_terminals took 0.0038s to import
      jupyter_server_terminals 0.4.4 OK
    jupyterlab enabled
    - Validating jupyterlab...
Package jupyterlab took 0.0464s to import
      jupyterlab 4.1.4 OK
    jupyterlab_h5web enabled
    - Validating jupyterlab_h5web...
Package jupyterlab_h5web took 0.0011s to import
      jupyterlab_h5web 12.0.0 OK
    notebook enabled
    - Validating notebook...
Package notebook took 0.0000s to import
      notebook 7.1.1 OK
    notebook_shim enabled
    - Validating notebook_shim...
Package notebook_shim took 0.0000s to import
A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
      notebook_shim  OK
    panel.io.jupyter_server_extension enabled
    - Validating panel.io.jupyter_server_extension...
Package panel.io.jupyter_server_extension took 0.6868s to import
      panel.io.jupyter_server_extension  OK

Config dir: /usr/local/etc/jupyter

</pre>
</details>

**Comment by loichuder** [comment]
Well spotted, thanks for reporting it !
