### ISSUE TITLE
Backport #133 to 8.x

### ISSUE THREAD

**Issue by rcthomas** [silx-kit/jupyterlab-h5web#135]
Can the access token fix in #133 please be applied retroactively on 8.x?  The same issue arises on JupyterLab 3.

**Comment by t20100** [comment]
@loichuder already made a [8.x](https://github.com/silx-kit/jupyterlab-h5web/tree/8.x) with a backport.

**Comment by rcthomas** [comment]
Thanks, I hadn't noticed that.  Is there a release planned for it (like 8.1)?

**Comment by loichuder** [comment]
Yep, once I managed to fix the CI :smile:

**Comment by loichuder** [comment]
All right, it did go through: v8.1 is out ! 

Please tell us how it went :wink:

**Comment by rcthomas** [comment]
Thanks again, does the conda-forge feedstock need a PR for this older version?

**Comment by t20100** [comment]
v8.1.0 should be available soon in conda-forge: https://github.com/conda-forge/jupyterlab-h5web-feedstock/pull/18
