### ISSUE TITLE
Issue 404 GET on macOS Catalina

### ISSUE THREAD

**Issue by ArnaudHemmerle** [silx-kit/jupyterlab-h5web#22]
Hello,

I've been trying to install the extension on my mac (Catalina) and I'm facing the following problem. I can't open a Nexus file, and this error message appears in the background :
```
[W 14:58:51.029 LabApp] 404 GET /hdf/meta/Documents/Recherche/Depository/JupyLabBook/recording/SIRIUS_Isotherm_2019_02_17_01544.nxs?uri=/ (::1) 5.790000ms referer=http://localhost:8889/lab
```

It seems like it is searching the file in a folder called ```/hdf/meta/```while it does not exist on my machine.

I've installed the extension with:
```

pip install jupyterlab_h5web
jupyter lab build
```
Here is what I get when I do ```jupyter serverextension list```
```
config dir: /Users/arnaudhemmerle/.jupyter
    jupyter_nbextensions_configurator  enabled 
    - Validating...
      jupyter_nbextensions_configurator 0.4.1 OK
config dir: /Users/arnaudhemmerle/anaconda3/etc/jupyter
    jupyterlab  enabled 
    - Validating...
      jupyterlab 2.2.9 OK
    jupyterlab_git  enabled 
    - Validating...
      jupyterlab_git 0.20.0 OK
    nbdime  enabled 
    - Validating...
      nbdime 2.1.0 OK
    voila.server_extension  enabled 
    - Validating...
      voila.server_extension  OK
    jupyter_nbextensions_configurator  enabled 
    - Validating...
      jupyter_nbextensions_configurator 0.4.1 OK
```

When I do ```jupyter labextension list```:
```
JupyterLab v2.2.9
Known labextensions:
   app dir: /Users/arnaudhemmerle/.local/share/jupyter/lab
        jupyterlab-h5web v0.0.5  enabled  OK
```

I've already tried to clean and build jupyterlab several times.

Thanks !

**Comment by loichuder** [comment]
Hello,

Thank you for trying the extension ! :slightly_smiling_face: 

It appears that `jupyterlab_hdf` is missing from your `serverextension list` which makes the request `/hdf/meta` fail. Try to enable it explicitly by running:
`jupyter serverextension enable jupyterlab_hdf`

(This might fail if `jupyterlab_hdf` is not installed so double-check that it is installed by looking at `pip list`)

**Comment by ArnaudHemmerle** [comment]
Perfect, this worked, thanks a lot :-) ! You may add the command you gave me to your troubleshoot section, for people like me who don't know it.
The extension seems to work very fine on our nexus data (SIRIUS beamline, SOLEIL). I've managed to display very quickly 0D data, spectrums, and images. Great !

**Comment by loichuder** [comment]
> Perfect, this worked, thanks a lot :-) ! You may add the command you gave me to your troubleshoot section, for people like me who don't know it.

Good call ! Thanks for the suggestion !

> The extension seems to work very fine on our nexus data (SIRIUS beamline, SOLEIL). I've managed to display very quickly 0D data, spectrums, and images. Great !

Glad to hear it :slightly_smiling_face: ! Do not hesitate to address any feedback to us !
