### ISSUE TITLE
File contents should not be fetched when opening through h5web

### ISSUE THREAD

**Issue by loichuder** [silx-kit/jupyterlab-h5web#24]
Waiting on https://github.com/jupyterlab/jupyterlab/pull/7596

**Comment by telamonian** [comment]
@loichuder In case you're still waiting, that got merged

**Comment by loichuder** [comment]
https://github.com/jupyterlab/jupyterlab/issues/10757

**Comment by loichuder** [comment]
I am closing this since I am quite happy with the fix of #65.

Using `format: null` is still a possibility but we may need to filter JupyterLab versions, which is a bit cumbersome.
