### ISSUE TITLE
region reference attributes are not supported

### ISSUE THREAD

**Issue by planetmarshall** [silx-kit/jupyterlab-h5web#30]
Attempting to open a dataset with a region reference attribute results in the following error:

```
TypeError: Object of type RegionReference is not JSON serializable
```

**Steps to reproduce**

Create the following HDF5 file:

```.py
import h5py
import numpy as np

with h5py.File("region_bug.h5", "w") as h5:
    data = h5.create_dataset("data", data=np.ones((3,3)))
    h5.attrs["dataref"] = data.regionref[0]
```

Attempt to open `region_bug.h5` in Jupyter Lab

**Comment by loichuder** [comment]
Thanks for the report ! This is a back-end issue but we can do something about it.

I did not use `RegionReference` myself so I would need a bit more info. 

Would you want the attribute value to be visible ? If so, what should it show ?
Or, would it be acceptable to skip completely the attribute ?

**Comment by planetmarshall** [comment]
I think ideally the attribute should show the referenced value, so for example

```.py
with h5py.File("region_bug.h5", "w") as h5:
    data = h5.create_dataset("data", data=np.array([1, 2, 42]))
    h5.attrs["answer"] = data.regionref[2]
```

Should be displayed as

**answer** 42

Though it should probably also indicate that it's a reference - the output of 

```
h5dump region_bug.h5
```

is 

```
HDF5 "region_bug.h5" {
GROUP "/" {
   ATTRIBUTE "answer" {
      DATATYPE  H5T_REFERENCE { H5T_STD_REF_DSETREG }
      DATASPACE  SCALAR
      DATA {
      (0): DATASET /data {(2)-(2)}
      }
   }
   DATASET "data" {
      DATATYPE  H5T_STD_I64LE
      DATASPACE  SIMPLE { ( 3 ) / ( 3 ) }
      DATA {
      (0): 1, 2, 42
      }
   }
}
}
```

So maybe

**answer** (ref /data {(2)-(2)})  42

**Comment by t20100** [comment]
Since the region reference can refer to any slicing in a dataset, displaying the values in the "Inspect" tab can be problematic.

**Comment by loichuder** [comment]
[v0.0.12](https://github.com/silx-kit/jupyterlab-h5web/releases/tag/v0.0.12) of the extension makes it compatible with h5grove latest version [v0.0.11](https://github.com/silx-kit/h5grove/releases/tag/v0.0.11) (the package serving HDF5 contents). This version no longer crash on `Reference` but converts them as strings. 

You can try by [updating](https://github.com/silx-kit/jupyterlab-h5web#update) the extension. This should install `h5grove` latest version (this can be ensured by running `pip install -U h5grove` afterwards).

I concur that converting references as strings does not give much useful info so I will try later to implement something more involved to at least give the name of the dataset it refers to.

**Comment by cherbon1** [comment]
Thank you for the update and for looking into this! I tested it and it to work fine.
I agree that converting to string isn't ideal, but it's a good enough fix for now for preventing crashes.
Thanks again!

**Comment by loichuder** [comment]
> I concur that converting references as strings does not give much useful info so I will try later to implement something more involved to at least give the name of the dataset it refers to.

I remember investigating this a while ago and it did not amount of anything because the reference needs outside information to be resolved. It was some weird stuff like it needs to have the file `id` of the entity it points to, which I don't know how to deduce consistently.

I am afraid we will have to do with strings for now.
