### ISSUE TITLE
Axes values with negative numbers are not properly displayed

### ISSUE THREAD

**Issue by Pepe-Marquez** [silx-kit/jupyterlab-h5web#80]
### Describe the bug

There seems to be a bug with the data displayed by h5web.  The axis positions are not properly placed.

Running on jupyter lab 3.2.9 and jupyterlab-h5web 1.3.0. 

The minimum and max values of the y axis (energy) are: −4.000e+0 to 1.000e+0
The minimum and max values of the x axis (delay) are: −2.000e+3 to 6.500e+3

### Screenshots

![image](https://user-images.githubusercontent.com/64071335/152564153-8713950f-0aa9-4ef0-b7a6-aa0df0fb6309.png)

### Context

- OS: ubuntu
- Browser: Chrome
- Version: 1.3.0
- JupyterLab version: 3.2.9 

<details><summary>Extension lists</summary>
<pre>

jupyter labextension list
JupyterLab v3.2.9
/home/.../jupyter/.py37env/share/jupyter/labextensions
        jupyterlab-h5web v1.3.0 enabled OK (python, jupyterlab_h5web)
        @jupyter-widgets/jupyterlab-manager v3.0.1 enabled OK (python, jupyterlab_widgets)

jupyter serverextension list
config dir: /home/pepe_marquez/.jupyter
    jupyterlab_h5web  enabled
    - Validating...
      jupyterlab_h5web 1.3.0 OK
config dir: /home/pepe_marquez/jupyter/.py37env/etc/jupyter
    jupyterlab  enabled
    - Validating...
      jupyterlab 3.2.9 OK
    jupyterlab_h5web  enabled
    - Validating...
      jupyterlab_h5web 1.3.0 OK
</pre>
</details>

**Comment by loichuder** [comment]
Thanks for the report

Could you provide us the file you were reading so that we can test it locally ourselves ?

Also, the Y axis label looks stretched. Did you zoom in the browser or have any kind of browser extension/tool that could mess up resolutions (remote desktop for example) ?

**Comment by axelboc** [comment]
I feel like we had a report of this exact issue a few months back, with the ordinate axis all stretched out, but couldn't reproduce. I've just tried on a fresh install of JupyterLab 3.2.9, in Chrome 98, on Ubuntu 20.04 and it seems to work fine.

@Pepe-Marquez could you please try to [start Chrome with extensions disabled](https://superuser.com/questions/254579/how-to-open-google-chrome-with-extensions-disabled-turned-off) and locally, outside of any remote desktop environment, as Loïc suggested? If that doesn't work, please try a different browser just to confirm that the problem relates to Chrome.

**Comment by loichuder** [comment]
I could reproduce the problem when zooming in the Chrome browser with <kbd>Ctrl</kbd>+ <kbd>Wheel</kbd>. Enabling `Large Text` in the Universal Access settings of Ubuntu also triggers the problem in Chrome.

Oddly, Firefox is unaffected.

@Pepe-Marquez My guess is that you have an OS/browser option enabled that would change the size of elements in the browser. You can try to disable it to see if it fixes the issue. 

In the meantime, we will investigate on why this happens on Chrome/Edge.

**Comment by axelboc** [comment]
Arf... With `0px`, SVGs get hidden, with `1px` they don't scale well... What's going to happen with `2px`!? 😂 Nice find @loichuder!

**Comment by loichuder** [comment]
>  What's going to happen with 2px!?

**Comment by Pepe-Marquez** [comment]
Thanks a lot! We will keep on reporting things from the FAIRmat team.
Cheers!
