### ISSUE TITLE
500 Error when trying to visualize datasets saved in `float128`

### ISSUE THREAD

**Issue by nicolasshu** [silx-kit/jupyterlab-h5web#84]
### Describe the bug

A 500 Error gets returned when a 3D array is passed to the framework. The screenshots below contain an image with a large number of the 0th dim, and another with only 67. The error log is as follows:

```
[E 2022-02-21 14:13:55.396 ServerApp] Uncaught exception GET /lab/api/settings?1645470835248 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/lab/api/settings?1645470835248', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/nickshu/anaconda3/envs/h5web/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
    tornado.iostream.StreamClosedError: Stream is closed
[I 2022-02-21 14:13:57.204 LabApp] Build is up to date
[E 2022-02-21 14:14:26.122 ServerApp] Uncaught exception GET /h5web/data/?file=MUSAN_FSD50K%2Fmusan_fsd50k_nooverlap_2s.h5&path=%2F40_mels%2Ftrain%2Ffeatures&selection=0,:,:&flatten=true (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/h5web/data/?file=MUSAN_FSD50K%2Fmusan_fsd50k_nooverlap_2s.h5&path=%2F40_mels%2Ftrain%2Ffeatures&selection=0,:,:&flatten=true', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/nickshu/anaconda3/envs/h5web/lib/python3.8/site-packages/tornado/web.py", line 1702, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/nickshu/anaconda3/envs/h5web/lib/python3.8/site-packages/tornado/web.py", line 3173, in wrapper
        return method(self, *args, **kwargs)
      File "/home/nickshu/anaconda3/envs/h5web/lib/python3.8/site-packages/jupyterlab_h5web/handlers.py", line 28, in get
        response = encode(content, format_arg)
      File "/home/nickshu/anaconda3/envs/h5web/lib/python3.8/site-packages/h5grove/encoders.py", line 109, in encode
        orjson_encode(content),
      File "/home/nickshu/anaconda3/envs/h5web/lib/python3.8/site-packages/h5grove/encoders.py", line 48, in orjson_encode
        return orjson.dumps(content, default=default, option=orjson.OPT_SERIALIZE_NUMPY)
    TypeError: default serializer exceeds recursion limit
[W 2022-02-21 14:14:26.123 ServerApp] Unhandled error
[E 2022-02-21 14:14:26.123 ServerApp] {
      "Host": "localhost:8888",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0",
      "Accept": "application/json, text/plain, */*",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept-Encoding": "gzip, deflate",
      "Connection": "keep-alive",
      "Referer": "http://localhost:8888/lab/workspaces/auto-x/tree/MUSAN_FSD50K",
      "Cookie": "username-localhost-8888=\"2|1:0|10:1645470865|23:username-localhost-8888|44:MTBmODU5YWVjN2QwNGM3OWI0ZGIyYTg3Mzg5NDBhMDc=|71d4f38e3541a61543b4765a12ca598a1413794e587db212ad204ec9317ff226\"; _xsrf=2|be7cd264|72c37ad1b680654d763a713d31046056|1643138022",
      "Sec-Fetch-Dest": "empty",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Site": "same-origin"
    }
[E 2022-02-21 14:14:26.123 ServerApp] 500 GET /h5web/data/?file=MUSAN_FSD50K%2Fmusan_fsd50k_nooverlap_2s.h5&path=%2F40_mels%2Ftrain%2Ffeatures&selection=0,:,:&flatten=true (127.0.0.1) 5.62ms referer=http://localhost:8888/lab/workspaces/auto-x/tree/MUSAN_FSD50K
```

### To Reproduce

Create an `.h5` file which contains a 3D array, and use the latest Jupyter Lab, and Jupyterlab H5web

### Expected behaviour

The expected behavior was to be able to see a slide heatmap of a 3D array

### Screenshots

![image](https://user-images.githubusercontent.com/12994607/155015112-4eeb7867-2b14-4921-a1b3-85ae41dc0259.png)

![image](https://user-images.githubusercontent.com/12994607/155015372-4f2b0cfb-2565-40e2-852f-eae3a3f08ae0.png)

### Context

- OS: Arch Linux
- Browser: Firefox
- Version: 
- JupyterLab version: 
```
jupyterlab==3.2.9
jupyterlab-h5web==2.0.0
jupyterlab-pygments==0.1.2
jupyterlab-server==2.10.3
```

<details><summary>Extension lists</summary>
<pre>

```
$ jupyter labextension list
JupyterLab v3.2.9
/home/user/anaconda3/envs/h5web/share/jupyter/labextensions
        jupyterlab-h5web v2.0.0 enabled OK (python, jupyterlab_h5web)

$ jupyter serverextension list
config dir: /home/user/anaconda3/envs/h5web/etc/jupyter
    jupyterlab  enabled
    - Validating...
      jupyterlab 3.2.9 OK
    jupyterlab_h5web  enabled
    - Validating...
      jupyterlab_h5web 2.0.0 OK
```
</pre>
</details>

**Comment by loichuder** [comment]
Thank you for the report !

Funny that you hit a recursion limit when trying to encode the data. I think it is because the dataset has a dtype we did not account for.

Could you tell us what is the dtype of the dataset you are trying to open ? Or, even better, could you provide us with the problematic file so we can test it out ourselves ? You can scrap other datasets to keep only the problematic one if you wish.

**Comment by nicolasshu** [comment]
Hi! 
Thank you very much! If you don't mind, is there something you can say for me to further understand this error? I'd love to know what led to this and where the problem lied in further detail!

Yes, I apologize for the delay. I had to go back into my scripts and re-create something that was a lot smaller b/c the files I was looking at were ~76GB. Actually, the h5web extension didn't work with any of them. [Here](https://github.com/nicolasshu/files_for_bugs/blob/main/jupyterlab_h5web/demo.h5) is a link for the file I've just uploaded for you!

Thank you very much!

**Comment by loichuder** [comment]
Great, thanks for the file : I think I was able to pinpoint the issue.

> If you don't mind, is there something you can say for me to further understand this error? I'd love to know what led to this and where the problem lied in further detail!

Sure. As I suspected, this is linked to the data type (or dtype for short) used to save the data. 

In your file, the datasets called `features` are saved using `float128` which is not supported by h5web yet.  You can check the data type in the `Inspect` tab, under **Type**:
![image](https://user-images.githubusercontent.com/42204205/155674345-21ba5589-292d-446d-9e13-29f15931390c.png)

**Now to solve the issue, we will have to bring support for `float128` datasets in h5web.**

However, if you have control over your saving process, the quickest way to solve the problem would be to save the data using `float64`. **:warning: Careful though, this will result in loss of numerical precision.**

For example, this dataset `features_64` (created from your `features` dataset but converted to `float64`) can be visualized just fine:
![image](https://user-images.githubusercontent.com/42204205/155674657-6a19f859-49e6-42ff-acd5-38c844aadff6.png)

**Comment by loichuder** [comment]
This will be fixed in next release (landing this week or the next). `float128` are now converted to `float64` for JSON serialization.

**Comment by nicolasshu** [comment]
Understood! Thank you very much!
